version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - wordpress
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  wordpress:
    image: wordpress:6.5-apache
    expose:
      - "80"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      # Fixed dynamic URL configuration that works with tunnels and nginx
      WORDPRESS_CONFIG_EXTRA: |
        // Dynamic URL configuration for tunneling through nginx
        if (!defined('WP_HOME')) {
            $$protocol = 'http';
            $$host = 'localhost:8080';
            
            // Check for forwarded protocol first (from nginx)
            if (isset($$_SERVER['HTTP_X_FORWARDED_PROTO'])) {
                $$protocol = $$_SERVER['HTTP_X_FORWARDED_PROTO'];
            }
            
            // Check for forwarded host (from nginx)
            if (isset($$_SERVER['HTTP_X_FORWARDED_HOST'])) {
                $$host = $$_SERVER['HTTP_X_FORWARDED_HOST'];
            } elseif (isset($$_SERVER['HTTP_HOST'])) {
                $$host = $$_SERVER['HTTP_HOST'];
            }
            
            // Special handling for loca.lt tunnels
            if (strpos($$host, 'loca.lt') !== false) {
                $$protocol = 'https';
            }
            
            define('WP_HOME', $$protocol . '://' . $$host);
            define('WP_SITEURL', $$protocol . '://' . $$host);
            
            // Force HTTPS for tunnel URLs
            if ($$protocol === 'https') {
                $$_SERVER['HTTPS'] = 'on';
                $$_SERVER['SERVER_PORT'] = '443';
            }
            
            // Handle reverse proxy headers properly
            if (isset($$_SERVER['HTTP_X_FORWARDED_FOR'])) {
                $$_SERVER['REMOTE_ADDR'] = explode(',', $$_SERVER['HTTP_X_FORWARDED_FOR'])[0];
            }
        }
        
        // Allow WordPress to handle different domains during install
        define('RELOCATE', true);
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - wordpress_data:/var/www/html
      - ../wordpress/wordpress.conf:/etc/apache2/sites-available/000-default.conf:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
    expose:
      - "3306"
    command: 
      - --skip-log-bin
      - --default-time-zone=+00:00
      - --innodb-buffer-pool-size=256M
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

volumes:
  mysql_data:
  wordpress_data: