version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - wordpress
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  wordpress:
    image: wordpress:6.5-apache
    expose:
      - "80"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      # Remove the hardcoded localhost URLs
      WORDPRESS_CONFIG_EXTRA: |
        // Dynamic URL configuration for tunneling
        if (isset($_SERVER['HTTP_HOST'])) {
            $host = $_SERVER['HTTP_HOST'];
            if (strpos($host, 'loca.lt') !== false || strpos($host, 'localhost') !== false) {
                define('WP_HOME', 'https://' . $host);
                define('WP_SITEURL', 'https://' . $host);
            }
        }
        
        // Fallback for localhost development
        if (!defined('WP_HOME')) {
            define('WP_HOME', 'http://localhost:8080');
            define('WP_SITEURL', 'http://localhost:8080');
        }
        
        // Force HTTPS for tunnel URLs
        if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') {
            $_SERVER['HTTPS'] = 'on';
        }
        
        // Handle reverse proxy headers
        if (isset($_SERVER['HTTP_X_FORWARDED_FOR'])) {
            $_SERVER['REMOTE_ADDR'] = $_SERVER['HTTP_X_FORWARDED_FOR'];
        }
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - wordpress_data:/var/www/html
      - ../wordpress/wordpress.conf:/etc/apache2/sites-available/000-default.conf:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
    expose:
      - "3306"
    command: 
      - --skip-log-bin
      - --default-time-zone=+00:00
      - --innodb-buffer-pool-size=256M
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

volumes:
  mysql_data:
  wordpress_data: