name: Test Apache WordPress Configuration

on:
  workflow_dispatch:

jobs:
  test-apache-config:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version
    
    - name: Build and test
      run: |
        cd docker
        docker-compose up -d --build
        
        # Wait for services to be healthy
        timeout 120 bash -c 'until docker-compose ps | grep "healthy"; do sleep 5; done' || echo "Health check timeout"
        
        # Test Apache configuration
        docker-compose exec -T wordpress apache2ctl configtest
        
        # Test if site is accessible
        curl -f http://localhost:8080 || exit 1
        
        # Test that sensitive files are blocked
        curl -f http://localhost:8080/wp-config.php && exit 1 || echo "wp-config.php properly blocked"
        
        # Show status
        docker-compose ps
        
        # Show logs for debugging
        docker-compose logs --tail=50
        
        # Cleanup
        docker-compose down
